# Generated by Django 2.2 on 2021-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='category_name',
            field=models.CharField(default='General', max_length=20),
        ),
    ]
